spring:
  # database connectivity
  datasource:
    url: jdbc:mariadb://localhost:3307/fileManager
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
  # H2 database console
  h2: # Eg: http://localhost:8080/h2-console
    console:
      enabled: true
# should not include trace error in response body (rest controller)
  main:
    allow-circular-references: true