spring:
  # database connectivity
  datasource:
    url: jdbc:mariadb://localhost:3307/carmng
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  # thymeleaf
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
  # H2 database console
  h2: # Eg: http://localhost:8080/h2-console
    console:
      enabled: true
# should not include trace error in response body (rest controller)
  main:
    allow-circular-references: true
jwt:
  secret: "ahihi01/01/1997+ok+ahihi01/01/1997+ok+ahihi01/01/1997+ok"  # Khóa bí mật cho JWT (bạn nên sử dụng giá trị mạnh và lưu trữ an toàn)
  expiration: 86400000 
server:
  port : 8000	